# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1a8a9541e80582cf015e35365085e466134a9bc2caa483205e99e6c32595189e4a4d344e415aa310e6f2ef9a6243f789bb480d8cfeac73b83db56a2d38793f6

test:
  secret_key_base: 0e5a010911eb05eb0a9e802ebbf20854f31f4265a3b8291c577a7db94965c7b65550a687f97d8148edd4c5b5fcfa100ac5a90144c74eb50bf0a205437e09e6a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
